name: lock-check

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lock-check:
    runs-on: ubuntu-latest
    steps:
      - uses: github/lock@v2.1.1
        id: lock
        with:
          mode: check
          environment: dev
          environment_targets: dev

      - name: Print lock status
        run: |
          echo "Lock status: ${{ steps.lock.outputs.locked }}"
